# The modifications of the output file from Kalibr:
# 1. For each matrix (e.g. cam0/T_cam_imu), remove the brackets and minus sign for each line. Use one pair of brackets for each matrix.
# 2. Add the T_imu_body at the end of the calibration file (usually set to identity).
cam0:
  T_cam_imu:
    [ 0.9999028098867836, -0.013078507996931393, -0.004829431549281497, 0.023131154795583586,
      0.013017494349084722, 0.9998376818824223, -0.012456112108352662, 0.0680383961563386,
      0.004991555006863211, 0.01239203439950455, 0.9999107569488664, -0.08882095938747082,
                     0,                   0,                   0,   1.000000000000000]
  camera_model: pinhole
  distortion_coeffs: [0.0107526, -0.0031166, -0.0002567, -0.001069]
  distortion_model: radtan
  intrinsics: [383.05963993854607, 385.05326770005917, 314.91684617363353, 238.39452595395264]
  resolution: [640, 480]
  timeshift_cam_imu: -0.04680223746711912
cam1:
  T_cam_imu:
    [0.9999133507005844, -0.012981068982214372, -0.002186993097636263, -0.07718168714570517,
     0.012952996607897177, 0.99983927567057, -0.012395269477737322, 0.06800747586061606,
     0.0023475454427808224, 0.012365867322145833, 0.9999207840402985, -0.0879497361137917,
                     0,                   0,                   0,   1.000000000000000]
  T_cn_cnm1:
    [0.9999965039567782, 6.464590399054658e-05, 0.002643462715049505, -0.10008236458294173,
     -6.480615233565015e-05, 0.9999999960678365, 6.0535007087941015e-05, -2.4044209637057163e-05,
     -0.0026434587913147243, -6.070610810234499e-05, 0.999996504214082, 0.000936189375350014,
     0.0, 0.0, 0.0, 1.0]
  camera_model: pinhole
  distortion_coeffs: [0.008132629254947288, 0.0006248681786484926, -3.3905015321507675e-05,
    -0.0009870579573504747]
  distortion_model: radtan
  intrinsics: [383.130360328568, 385.2556845780806, 314.08760061257743, 238.29074050583466]
  resolution: [640, 480]
  timeshift_cam_imu: -0.04664317928566175
T_imu_body:
  [1.0000, 0.0000, 0.0000, 0.0000,
  0.0000, 1.0000, 0.0000, 0.0000,
  0.0000, 0.0000, 1.0000, 0.0000,
  0.0000, 0.0000, 0.0000, 1.0000]

